### ISSUE TITLE
other CF units Python package

### ISSUE THREAD

**Issue by zmoon** [NCAS-CMS/cfunits#17]
I am curious how this package compares to this one: https://github.com/SciTools/cf-units

Maybe a little about that could be included in the readme or documentation?

**Comment by davidhassell** [comment]
Hi @zmoon,

Not much difference. They are both wrappers to the UDUNITS2 C library that serve a larger analysis library, but are also available as stand-alone libraries. So it comes down to which API and available functionality you might prefer.

**Comment by sadielbartholomew** [comment]
@zmoon, unless you have any follow-up questions, I think this has been clarified and so this issue can be closed? We don't really think it is necessary or relevant to add anything to our documentation about some other, independent, library.

**Comment by zmoon** [comment]
I think it is relevant and would be helpful to potential users, but yes, not necessary, feel free to close. Thanks.

**Comment by sadielbartholomew** [comment]
Thanks @zmoon.

> I think it is relevant

Fair enough. Just to clarify our stance, I can understand why that information is relevant in itself, but putting such information in the main documentation doesn't seem the best location for us. Having this Issue is sufficient to document the question and answer regarding difference to 'cf-units'. Though if we get the impression many others share the same question and don't find this thread, we can and will revise that plan.
